
filter:
  excluded_paths: [tests/*]


build:
  nodes:
    analysis:
      tests:
        before:
          - py-scrutinizer-run

        override:
          - command: make test-all
            coverage:
              file: .coverage
              format: py-cc

