version: 2.1

jobs:
    build:
        docker:
            # specify the version you desire here
            - image: cimg/python:3.8.10


        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

            - run:
                name: Install Python deps in a venv
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - "venv"

            # run tests!
            - run:
                name: run tests, pylint and code coverage
                command: |
                    . venv/bin/activate
                    make test-all