name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the main Docker image
      run: docker build . --file Dockerfile_main --tag ranim04/spark-program:main

    - name: Docker Push main program
      run: docker push ranim04/spark-program:main
    
    - name: Build the simulation Docker image
      run: docker build . --file Dockerfile_simulation --tag ranim04/spark-program:simulation

    - name: Docker Push simulation program
      run: docker push ranim04/spark-program:simulation
    
    
